# ansible-galaxy install stackhpc.libvirt-host
# Read: https://galaxy.ansible.com/stackhpc/libvirt-host
# Read: https://github.com/stackhpc/ansible-role-libvirt-host
- hosts: all
  #connection: local
  gather_facts: yes

  name: Ensure that Libvirt is configured
  
  become: yes

  pre_tasks:
  
   # Required for rudimentary Fedora 36 support as per:
   # https://github.com/stackhpc/ansible-role-libvirt-host/issues/57
   - name: Override the OS version so the role works
     ansible.utils.update_fact:
       updates:
         - path: ansible_facts.os_family
           value: RedHat
         - path: ansible_facts.distribution
           value: RedHat
         - path: ansible_facts.distribution_major_version
           value: 8
         - path: ansible_facts.distribution_version
           value: 8
     tags:
     - os

   - name: Check the OS version was overridden correctly
     debug:
       msg: Family "{{ ansible_facts.os_family }}", distro "{{ ansible_facts.distribution }}", major ver "{{ ansible_facts.distribution_major_version }}"
       #msg: major ver "{{ ansible_facts.distribution_major_version }}"
       #msg: distro "{{ ansible_facts.distribution }}", major ver "{{ ansible_facts.distribution_major_version }}"
     tags:
     - os

#   - name: Install genisoimage package so we can create new qcow seed images
#     dnf:
#       name: genisoimage
#       state: latest

  roles:
    - role: stackhpc.libvirt-host
      become: no
      libvirt_host_networks:
        - name: vm-network-routed
          mode: route
          bridge: virbr1
          domain: "{{ libvirt_domain }}"
          ip: "{{ libvirt_ip }}"
          netmask: "{{ libvirt_netmask }}"
          dhcp_start: "{{ libvirt_dhcp_start }}"
          dhcp_end: "{{ libvirt_dhcp_end }}"
      libvirt_host_pools:
        - name: vm-pool
          type: dir
          #capacity: 1024
          path: /var/lib/libvirt/vm-pool
          mode: 755
          owner: qemu
          group: qemu

  post_tasks:

#  - name: Install cloud utilities
#    dnf:
#      name: cloud-utils
#      state: present

    - name: Create /var/lib/libvirt/images dir
      ansible.builtin.file:
        path: /var/lib/libvirt/images
        state: directory
        owner: root
        group: root
        mode: '0755'
      tags:
        - cloud-init

    - name: Copy cloud-init ISO
      ansible.builtin.copy:
        src: files/generic_vm/generic-seed.iso
        dest: "{{ item }}"
        owner: qemu
        group: qemu
        mode: '0644'
      loop:
        - /mnt/vm_images/generic-seed.iso
        - /var/lib/libvirt/images/generic-seed.iso
      tags:
        - cloud-init
