# ansible-galaxy install stackhpc.libvirt-vm
# Read: https://galaxy.ansible.com/stackhpc/libvirt-vm
# Read: https://github.com/stackhpc/ansible-role-libvirt-vm
#
# Example playbook execution:
# ansible-playbook libvirt-newvm.yml --ask-become-pass -e "distribution_version='rhel86'"
# Note: Default state is present, and default RHEL version is defined by "distribution_version"
#
- name: Install a VM using a role

  hosts: "{{ hypervisor_host | default('all') }}"

  vars_files:
    - vars/vm_image.yml
    # Probably a misuse of defaults, as defaults/main.yml is a construct used in roles
    - defaults/main.yml

  vars:

    libvirt_domain: "{{ ansible_hostname }}.blasco.id.au"

    # Define a default version unless overridden when calling the playbook
    vm_name: "{{ vm_hostname | default(distribution_version) }}"
    #vm_name: "{{ vm_hostname | default(vm_image [distribution_version]) }}"

  pre_tasks:
     - name: Print the variables
       debug:
         msg: RHEL version is "{{ distribution_version }}" and hostname is "{{ vm_name }}"

#     # Temporary action due to a bug between libvirtd and some other Linux service (dbus?)
#     - name: Restart libvirtd
#       become: yes
#       service:
#         name: libvirtd
#         state: restarted
#     
#     - name: Pause while libvirtd restarts
#       ansible.builtin.pause:
#         seconds: 12

  roles:
    - role: ansible-role-libvirt-vm
      libvirt_vms:
        - state: "{{ vm_state | default('present') }}"
          name: "{{ vm_name }}.{{ libvirt_domain }}"
          memory_mb: "{{ memory_mb }}"
          vcpus: "{{ vcpus }}"
          volumes:
            - name: "{{ vm_name }}"
              device: 'disk'
              #type: 'file'
              format: 'qcow2'
              # capacity: '20GB'
              capacity: "{{ disk_size }}"
              pool: 'vm-pool'
              image: "{{ vm_image_path + vm_image [ distribution_version ] }}"
            - name: 'generic-seed.qcow2'
              type: 'file'
              device: 'cdrom'
              format: 'raw'
              #image: '/var/lib/libvirt/images/generic-seed.qcow2'
              # Path below seems to be ignored, forcing me to have the file
              # in /var/lib/libvirt/images
              image: "{{ vm_image_path }}generic-seed.qcow2"
          interfaces:
            - network: 'vm-network-routed'
          autostart: no
          boot_firmware: "{{ boot_mode }}"
          enable_guest_virtio: true

  post_tasks:
     - name: Record the stats about the new VM
       ansible.builtin.set_stats:
         data:
           vm_fqdn: "{{ vm_name }}.{{ libvirt_domain }}"
         per_host: false
